name: pgblackboard
services:

  dev:
    build: { context: '.', target: dev }
    ports: [7890:7890]
    tty: true
    command: [cargo, run, --
      , '--verbosity=debug'
      , 'postgres://postgres:5432?application_name=pgbb-dev']
    volumes: [.:/app]
    develop:
      watch:
        - { path: dockerfile, action: rebuild }
        - { path: ./server, action: restart }
    # deploy:
    #   resources:
    #     limits:
    #       memory: 20M

  prod:
    build: .
    ports: [7890:7890]
    read_only: true
    command: [pgbb, 'postgres://postgres:5432?application_name=pgbb-prod']

  pg18:
    image: kagiskz/postgres:18.1-20251218
    networks:
      default:
        aliases:
          - postgres

  pg10:
    image: postgres:10.23-alpine3.16
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      default:
        aliases:
          - postgres
